### ISSUE TITLE
cannot load such file -- rails-assets-picturefill (LoadError)

### ISSUE THREAD

**Issue by poulping** [tomasc/picture_tag#3]
Hello,
picture_tag.rb requires `rails-assets-picturefill`, and in my case it will fail if I do not add this to the gemfile:

```ruby
source 'https://rails-assets.org' do
  gem 'rails-assets-picturefill'
end
```

So I guess the docs should mention it in the installation chapter ?

Thanks for sharing your efforts!

**Comment by tomasc** [comment]
Good idea, added, thank you!
